config/routes.rb
Rails.application.routes.draw do
  resources :customers
  resources :profiles
  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # This model can have many attached documents under the `contracts` association
  has_many_attached :contracts

  # This instruction is part of the code that allows us destroy contracts via a customer's update action
  accepts_nested_attributes_for :contracts_attachments, allow_destroy: true
end

app/models/profile.rb
class Profile < ApplicationRecord
  # This model can have one attached document called `avatar`
  has_one_attached :avatar

  # This instruction is part of the code that allows us destroy an avatar via a profile's update action
  accepts_nested_attributes_for :avatar_attachment, allow_destroy: true

  # Example of how to reject a document if its size is too big
  validate :avatar_byte_size, if: ->{ avatar.attached? }

  private

  def avatar_byte_size
    errors.add :avatar, 'too big' if avatar.byte_size > (1024 ** 2)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      redirect_to @customer, notice: 'Customer was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    if @customer.update(customer_params)
      redirect_to @customer, notice: 'Customer was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    redirect_to customers_url, notice: 'Customer was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(
        :name,
        contracts: [], # Allows upload of multiple files
        contracts_attachments_attributes: [:id, :_destroy] # Allows destruction of contracts through `accept_nested_attributes_for`
      )
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)
    if @profile.save
      redirect_to @profile, notice: 'Profile was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    if @profile.update(profile_params)
      redirect_to @profile, notice: 'Profile was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    redirect_to profiles_url, notice: 'Profile was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(
        :last_name, :first_name,
        :avatar, # Allows upload of a single file
        avatar_attachment_attributes: [:id, :_destroy] # Allows destruction of an avatar through `accept_nested_attributes_for`
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/customers/_form.html.erb
<%= form_with(model: customer, local: true) do |form| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :contracts %>
    <!-- Allow the user to upload multiple files at once -->
    <!-- Notice the `multiple: true` here -->
    <%= form.file_field :contracts, multiple: true %>

    <!-- Display a thumbnail for each attached and persisted contract -->
    <% if customer.contracts.attached? %>
      <br />
      <% customer.contracts.each do |contract| %>
	<%= image_tag(contract.representation(resize: '250x250')) if contract.persisted? %>
      <% end %>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Customers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.name %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @customer.name %>
</p>

<p>
  <strong>Contracts:</strong><br />

  <!-- Loop on each attached contract -->
  <% @customer.contracts.each do |contract| %>
    <!-- Display attachment id and filename -->
    #<%= contract.id %>: <%= contract.filename %><br />

    <!-- Display the image in a resized format -->
    <%= image_tag(contract.representation(resize: '300x300').processed)  %>
    <br />

    <!-- Link to download the image in its original size -->
    <!-- This is a redirection link that should be valid 5 minutes -->
    <%= link_to 'Download file', rails_blob_path(contract, disposition: 'attachment') %>
    <br />

    <!-- Display some information about the file -->
    <p>
      <strong>Metadata:</strong><br /><%= contract.metadata %><br />
      <strong>Byte size:</strong><br /><%= contract.byte_size %><br />
    </p>
  <% end %>
</p>

<!-- This is a block that allows the user to manually choose which files to delete -->
<% if @customer.contracts.attached? %>
  <div style="background-color: #ccc; padding: 15px">
    <p>Delete contracts:</p>

    <%= form_for @customer do |f| %>
      <% @customer.contracts.each do |contract| %>

	<!-- For each contract, we call `fields_for` and add two elements to the form content: -->
	<!-- 1. the id of the contract -->
	<!-- 2. a checkbox that lets the user decide whether or not to delete this contract -->
	<!-- We also display here a thumbnail of the contract instead of a label. Personal choice. -->
	<%= f.fields_for :contracts_attachments_attributes do |contract_form| %>
	  <%= contract_form.hidden_field :id, value: contract.id %>
	  <%= contract_form.check_box :_destroy %>
	  <%= image_tag(contract.representation(resize: '50x50').processed)  %>
	  <br />
	<% end %>

      <% end %>
      <%= f.submit "Delete contracts" %>
    <% end %>

  </div>
<% end %>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoActivestorage</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <ul>
      <li><%= link_to 'Profiles', profiles_path %></li>
      <li><%= link_to 'Customers', customers_path %></li>
    </ul>
    <hr />
    <%= yield %>
  </body>
</html>

app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :avatar %>
    <!-- Upload an avatar -->
    <%= form.file_field :avatar %>

    <!-- Avoid raising errors by manipulating an avatar that does not exist or that is not representable (meaning ActiveStorage wouldn't know how to generate a thumbnail out of it) -->
    <% if profile.avatar.attached? && profile.avatar.representable? %>
      <br />
      <!-- Display a thumbnail of the uploaded file when validations fail and form is re-rendered -->
      <!-- We use #processed to generate the resized version only once and reuse it as many times as necessary -->
      <%= image_tag(profile.avatar.representation(resize: '250x250').processed) %>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Last name</th>
      <th>First name</th>
      <th>Avatar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.last_name %></td>
        <td><%= profile.first_name %></td>
	<!-- Render a thumbnail if an avatar is attached and representable (meaning one that ActiveStorage knows how to generate a thumbnail out of) -->
	<!-- By using `processed`, we ask ActiveStorage to generate it only once and store it for later reuse -->
        <td><%= image_tag(profile.avatar.representation(resize: '50x50').processed) if profile.avatar.attached? && profile.avatar.representable? %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Last name:</strong>
  <%= @profile.last_name %>
</p>

<p>
  <strong>First name:</strong>
  <%= @profile.first_name %>
</p>

<p>
  <strong>Avatar:</strong><br />

  <!-- Avoid raising errors by manipulating an avatar that does not exist -->
  <% if @profile.avatar.attached? %>

    <!-- Display the image in its original size -->
    <%= image_tag(@profile.avatar)  %>
    <br />

    <!-- Link to download the image in its original size -->
    <!-- This is a redirection link that should be valid 5 minutes -->
    <%= link_to 'Download file', rails_blob_path(@profile.avatar, disposition: 'attachment') %>
    <br />

    <!-- Button to destroy the image using `accepts_nested_attributes_for` feature -->
    <%= form_for @profile do |f| %>
      <%= f.fields_for :avatar_attachment_attributes do |avatar_form| %>
	<%= avatar_form.hidden_field :id, value: @profile.avatar_attachment.id %>
	<%= avatar_form.hidden_field :_destroy, value: true %>
      <% end %>
      <%= f.submit "Delete avatar" %>
    <% end %>

    <!-- Display some information about the file -->
    <p>
      <strong>Metadata:</strong><br /><%= @profile.avatar.metadata %><br />
      <strong>Byte size:</strong><br /><%= @profile.avatar.byte_size %><br />
    </p>
  <% end %>
</p>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>